CreditSuisse/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CreditSuisse.Models
{
    public class LoginViewModel
    {
        [Display(Name = "Username")]
        [Required(ErrorMessage = "This field is required.")]
        [StringLength(30, ErrorMessage = "Length between 5 and 30 characters.", MinimumLength = 5)]
        [DataType(DataType.Text)]
        public string User { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required.")]
        [StringLength(15, ErrorMessage = "Length between 5 and 15 characters.", MinimumLength = 5)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Rememberme")]
        public bool RememberMe { get; set; }
    }
}

CreditSuisse/Areas/banxico/Controllers/APIController.cs
using banxico;
using banxico.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;

namespace CreditSuisse.Areas.banxico.Controllers
{
    public class APIController : Controller
    {
        JsonSerializerSettings jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };

        // GET: banxico/API/SIE/SP74665
        public ActionResult SIE(string serie)
        {
            ViewBag.Serie = serie;
            string url = ConfigurationManager.AppSettings["Url"];
            string token = ConfigurationManager.AppSettings["Token"];
            List<DataPoint> data = SIERest.ReadSerie(serie, url, token);
            ViewBag.DataPoints = JsonConvert.SerializeObject(data, jsonSetting);

            if (data.Count > 0)
                return View();
            else
                return RedirectToAction("Index", "Home", new { Area = "" });
        }
    }
}

CreditSuisse/Controllers/HomeController.cs
using CreditSuisse.Areas.banxico.Controllers;
using CreditSuisse.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CreditSuisse.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Session["UserName"] != null)
                return RedirectToAction("Home");

            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginViewModel loginDataModel)
        {
            if (Session["UserName"] != null)
                return RedirectToAction("Home");

            if (ModelState.IsValid)
            {
                if (UserValidation(loginDataModel))
                {
                    return RedirectToAction("Home");
                }
            }

            return View(loginDataModel);
        }

        public ActionResult Logout()
        {
            if (Session["UserName"] != null)
                Session["UserName"] = null;

            return RedirectToAction("Home");
        }

        public ActionResult Home()
        {
            return View();
        }

        private bool UserValidation(LoginViewModel loginDataModel)
        {
            string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;

            bool ValidateUser = false;
            using (DBConnection DB = new DBConnection())
            {
                DB.ClearParameters();
                DB.AddParameter("@User", loginDataModel.User);
                DB.AddParameter("@Password", loginDataModel.Password);
                ValidateUser = DB.ExecuteStoredProcedureToValue<bool>("[dbo].[sp_validateUser]");
            }
                
            if (ValidateUser)
            {
                Session["UserName"] = loginDataModel.User;
                return true;
            }

            return false;
        }
    }
}

CreditSuisse/Areas/banxico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Credit Suisse - @ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Images/favicon.png")" />
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="@Url.Content("~/Images/logo.svg")" alt="logo" class="img-logo" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Non-Core Inflation", "SIE", "API", new { area = "banxico", serie = "SP74665" }, new { })</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Credit Suisse by Emmanuel Rico.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CreditSuisse/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>.NET SR</h1>
    <p class="lead">DEVELOPER CHALLENGE</p>
</div>

<h1>Get ready!</h1>

<div class="row">
    <div class="col-md-3">
        <p class="sc-section">
            You'll need your computer set up for
            development with VisulStudio 2017 or
            2019!
        </p>
    </div>
    <div class="col-md-3">
        <p class="sc-section">
            Read the instructions and requirements for
            the challenge.
        </p>
    </div>
    <div class="col-md-3">
        <p class="sc-section">
            You have up to 3 days* to submit your
            solution and keep in mind that we would
            like that you share your best work and
            something you are really proud of.
        </p>
    </div>
    <div class="col-md-3">
        <p class="sc-section">
            Please use Git to version your changes and
            make sure to include the .git directory with
            your submission. If you want to keep your
            code private, you can create a free account
            on Bitbucket.
        </p>
    </div>
</div>

<div>
    <h2>Keep this in mind</h2>
    <ul>
        <li>It's not required to complete all the levels.</li>
        <li>Logical Programming, is to solve things in the simplest and most optimal way possible.</li>
        <li>The developed levels will be evaluated.</li>
        <li>Implementation of basic development concepts (SOLID).</li>
        <li>Use of design patterns.</li>
        <li>Unit tests.</li>
        <li>Documentation.</li>
        <li>Security.</li>
    </ul>
</div>

<hr />
<h1>Level 1.  "to graph is to draw"</h1>

<div class="row">
    <div class="col-md-4">
        <p class="sc-section">
            Create a website that shows the different
            perspectives for the indicator "Non-core inflation"
            on a dashboard.
        </p>
    </div>
    <div class="col-md-4">
        <p class="sc-section">
            Obtain metadata in JSON format by
            implementing the SIE API of Banco de México
        </p>
    </div>
    <div class="col-md-4">
        <p class="sc-section">
            SIE API of Banco de México<br />
            <a href="https://www.banxico.org.mx/SieAPIRest/service/v1/">https://www.banxico.org.mx/SieAPIRest/service/v1/</a><br />
            Method:: GET series/:idSerie/datos<br />
            IdSerie = SP74665  (Inflación No subyacente)
        </p>
    </div>
</div>

<div>
    <h2>Keep this in mind</h2>
    <ul>
        <li>Please read the API documentation carefully.</li>
        <li>Perform unit tests to verify your connection to the service.</li>
        <li>Pre-develop your algorithm.</li>
    </ul>
</div>

<hr />
<h1>Level 2.  "Let's rock"</h1>

<div class="row">
    <div class="col-md-6">
        <p class="sc-section">
            Create an authentication page for the level 1 website.
        </p>
    </div>
    <div class="col-md-6">
        <p class="sc-section">
            You can use basic username/password
            authentication, but try implementing MFA or OAuth2
        </p>
    </div>
</div>

<div>
    <h2>Keep this in mind</h2>
    <ul>
        <li>If you create DB objects (tables, stored procedures) that are for SQL server.</li>
        <li>You must include the script in your solution.</li>
    </ul>
</div>

<hr />
<h1>Bonus</h1>

<div class="row">
    <div class="col-md-4">
        <p class="sc-section">
            Role-based access control (and its management) to
            restrict system access to diferent user operations.
        </p>
    </div>
    <div class="col-md-4">
        <p class="sc-section">
            Send a notification to the system administrator in
            case of incorrectly entering the user password for
            the third time.
        </p>
    </div>
    <div class="col-md-4">
        <p class="sc-section">
            Use your imagination and creativity to WOW us.
            Think of cool and useful features or functionalities
            that you can add to this application. Implement
            them as part of your solution to the challenge!
        </p>
    </div>
</div>

CreditSuisse/Views/Home/Index.cshtml
@model CreditSuisse.Models.LoginViewModel

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
        <div class="col-md-4 col-sm-3"></div>
        <div class="col-md-3 col-sm-6">
            <br />
            @Html.LabelFor(x => x.User, new { @class = "" })
            @Html.TextBoxFor(x => x.User, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(x => x.User, null, new { @class = "text-danger" })
            <br />

            @Html.LabelFor(x => x.Password)
            <div class="input-group">
                @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                <span class="input-group-btn">
                    <button id="verPassword" class="btn btn-default" type="button">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </button>
                </span>
            </div>
            @Html.ValidationMessageFor(x => x.Password, null, new { @class = "text-danger" })
            <br />

            <button class="btn btn-primary" type="submit">
                Login
            </button>
            <br />
        </div>
        <div class="col-md-5 col-sm-3"></div>
    }
</div>

@section scripts {

    <script>
        $('#verPassword').on('mousedown', function () {
            $('#Password').attr("type", "text");
        });

        $('#verPassword').on('mouseup mouseleave', function () {
            $('#Password').attr("type", "password");
        });
    </script>
}

CreditSuisse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Credit Suisse - @ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Images/favicon.png")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="@Url.Content("~/Images/logo.svg")" alt="logo" class="img-logo" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{ if (this.Session["UserName"] != null)
                        {
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Non-Core Inflation", "SIE", "API", new { area = "banxico", serie = "SP74665" }, new { })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { })</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Credit Suisse by Emmanuel Rico.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>